---
- name: Test My App
  hosts: serverq.lab.example.com
  connection: local
  tasks:
    - name: Test my app 
      uri:
        url: http://serverq.lab.example.com
        return_content: yes
      register: this
      failed_when: “’Welcome’ not in this.content” 
